# Generated by Django 4.1.5 on 2023-01-31 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item_manager', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
