# Generated by Django 4.1.5 on 2023-02-01 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('item_manager', '0002_delete_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('count', models.IntegerField()),
            ],
        ),
    ]
